### ISSUE TITLE
按照教程启动项目报错

### ISSUE THREAD

**Issue by Hudiebbk** [silentbalanceyh/vertx-zero#208]
![image](https://user-images.githubusercontent.com/30064286/128586062-2e2e112f-88f2-4e34-a8c0-05b1232df7b5.png)

**Comment by silentbalanceyh** [comment]
这个错误是遗留问题，不影响启动，但下边那个错误可能是未加载正确的类，需检查

**Comment by silentbalanceyh** [comment]
下边那个错误我看到过，貌似是JDK的问题，启动需使用JDK8，生产环境下比较稳定，目前的版本还没考虑过升级到最新的JDK。

**Comment by Hudiebbk** [comment]
![image](https://user-images.githubusercontent.com/30064286/128586781-22213afa-ffd0-40b0-80f5-727dc71017a9.png)
![image](https://user-images.githubusercontent.com/30064286/128586787-4a65d2fd-143c-4031-8cec-57b16ddac56b.png)
没有做任何多余的事情

**Comment by Hudiebbk** [comment]
切换jdk1.8就可以了
