### ISSUE TITLE
netty的依赖问题

### ISSUE THREAD

**Issue by dai875939260** [silentbalanceyh/vertx-zero#275]
netty-transport 和 netty-all冲突，构建工具是gradle。默认是不是应该加上option：true，或者拆分模块，不然默认导入了所有依赖

**Comment by silentbalanceyh** [comment]
Zero目前我们用的是Maven，没使用Gradle，应该直接加上这个选项

**Comment by pipinet** [comment]
可以暂时自主解决。。
compile("cn.vertxup:vertx-import:$vertxupVersion"){
        exclude group: 'io.netty'
    }
    compile("io.netty:netty-all:$nettyVersion")

**Comment by silentbalanceyh** [comment]
Solution：
参考 pipinet的回复
```groovy
compile("cn.vertxup:vertx-import:$vertxupVersion"){
        exclude group: 'io.netty'
}
compile("io.netty:netty-all:$nettyVersion")
```
