### ISSUE TITLE
关于WorkerExecutor 

### ISSUE THREAD

**Issue by ooocici** [silentbalanceyh/vertx-zero#328]
框架是否提供创建WorkerExecutor 方法?
如果没有提供,我该如何获取vertx实例对象呢?

**Comment by silentbalanceyh** [comment]
参考：http://www.vertxup.cn/doc/vertx-zero-tutorial/d10015-by-typed-parameters.html

**Comment by silentbalanceyh** [comment]
框架本身不能在Rest流程中去创建流程上使用的Worker，但可以直接创建其他Worker，如果要深度定制就只有重写Agent，启动的时候日志中有说明使用了哪个Agent，默认是Rest的。

**Comment by ooocici** [comment]
好的, 昨晚也看见了Worker的示例,也是想着是不是利用它去完成工作。
多谢！

**Comment by silentbalanceyh** [comment]
Zero中的后边部分已经使用了Worker，你可以看看官方文档中关于这部分内容中的第二部分：
2. Async Non-Blocked
D10018 ~ D10025
这里面包含了不同的写法，里面有图解，关于Zero中支持的同步、异步等各种模式。

**Comment by silentbalanceyh** [comment]
Solution：
参考：http://www.vertxup.cn/doc/vertx-zero-tutorial/d10015-by-typed-parameters.html
