### ISSUE TITLE
读逐陆记一些问题

### ISSUE THREAD

**Issue by liushunqiu** [silentbalanceyh/vertx-zero#335]
你好，我想问一下，使用Launcher启动部署多个Verticle, 在项目中部署一个eventloop的verticle,然后是否需要部署多个worker的verticle，例如数据库操作的，webclient的这些。~感谢回答。

**Comment by silentbalanceyh** [comment]
这个Worker看你自己，可以是多种，如果是同一类（一个Class的，用instance就可以直接设置了）

**Comment by silentbalanceyh** [comment]
有什么问题你直接Q我吧：445191171

**Comment by baodingfengyun** [comment]
有QQ群，或微信群吗？

**Comment by silentbalanceyh** [comment]
445191171 我的微信

发自我的 iPhone
