### ISSUE TITLE
ERR-60036的模板信息格式有误

### ISSUE THREAD

**Issue by staticdone** [silentbalanceyh/vertx-zero#391]
io.vertx.up.exception._500RpcTransitInvokeException: [ERR-60036] (FinalTransit) Web Exception occus: (500) - (Rpc) Transit invoke met error, transit class = null, method = public io.vertx.core.Future com.xxx.XXXIpc.add(io.vertx.up.atom.Envelop), details = {2}.

transit class = null 和 details = {2}. 有误

**Comment by silentbalanceyh** [comment]
这个问题已解决，不过还没发布对应的版本。

**Comment by silentbalanceyh** [comment]
参考PR：https://github.com/silentbalanceyh/vertx-zero/pull/393
